type ImportReference = {
  importPath: string;
  importedIdentifier: string;
};

type AnalyzedTaskStep = ImportReference & {
  id?: string;
};

type AnalyzedTask = {
  entityName?: string;
  name: string;
  runtime?: string;
  taskId?: string;
  steps?: AnalyzedTaskStep[];
};

export type OntahiApplicationCodegenModel = {
  tasks?: AnalyzedTask[];
};

export type VercelWorkflowCodegenOptions = {
  application: OntahiApplicationCodegenModel;
  runtimeImportPath: string;
  stepsImportPath: string;
  stepRunnerImport?: ImportReference;
  runtime?: string;
};

export type VercelWorkflowCodegenDiagnostic = {
  code:
    | 'task-id-unresolved'
    | 'task-id-duplicate'
    | 'task-step-id-unresolved'
    | 'task-step-id-duplicate';
  message: string;
  taskName: string;
  stepExportName?: string;
};

export type VercelWorkflowCodegenResult = {
  diagnostics: VercelWorkflowCodegenDiagnostic[];
  stepsSource: string;
  workflowSource: string;
};

type WorkflowStepDescriptor = {
  id: string;
  exportName: string;
};

type WorkflowDescriptor = {
  taskId: string;
  workflowExportName: string;
  stepRunnerExportName: string;
  steps: WorkflowStepDescriptor[];
};

const GENERATED_HEADER =
  '// This file is generated by @ontahi/runtime-vercel-workflows/codegen. Do not edit by hand.';

const identifierWords = (value: string) =>
  value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map(word => word.toLowerCase());

const capitalize = (value: string) => `${value[0]?.toUpperCase() ?? ''}${value.slice(1)}`;

const toLowerCamel = (words: string[]) =>
  words.map((word, index) => (index === 0 ? word : capitalize(word))).join('');

const combineTaskAndStepWords = (taskWords: string[], stepWords: string[]) => {
  let overlap = Math.min(taskWords.length, stepWords.length);

  while (
    overlap > 0 &&
    taskWords.slice(-overlap).join('.') !== stepWords.slice(0, overlap).join('.')
  ) {
    overlap -= 1;
  }

  return [...taskWords.slice(0, taskWords.length - overlap), ...stepWords];
};

const uniqueIdentifier = (preferredName: string, usedNames: Set<string>) => {
  let candidate = preferredName;
  let suffix = 2;

  while (usedNames.has(candidate)) {
    candidate = `${preferredName}${suffix}`;
    suffix += 1;
  }

  usedNames.add(candidate);
  return candidate;
};

const createWorkflowDescriptors = (application: OntahiApplicationCodegenModel, runtime: string) => {
  const diagnostics: VercelWorkflowCodegenDiagnostic[] = [];
  const descriptors: WorkflowDescriptor[] = [];
  const usedExportNames = new Set<string>();
  const usedTaskIds = new Set<string>();

  for (const task of application.tasks ?? []) {
    if (task.runtime !== runtime) {
      continue;
    }

    if (!task.taskId) {
      diagnostics.push({
        code: 'task-id-unresolved',
        message: `${task.entityName ?? 'Task'}.${task.name} must expose a statically resolved task id for Vercel Workflow codegen.`,
        taskName: task.name,
      });
      continue;
    }

    if (usedTaskIds.has(task.taskId)) {
      diagnostics.push({
        code: 'task-id-duplicate',
        message: `${task.taskId} is declared by more than one ${runtime} task.`,
        taskName: task.name,
      });
      continue;
    }
    usedTaskIds.add(task.taskId);

    const taskWords = identifierWords(task.taskId);
    const workflowExportName = uniqueIdentifier(
      `${toLowerCamel(taskWords)}Workflow`,
      usedExportNames,
    );
    const stepRunnerExportName = uniqueIdentifier(
      `run${capitalize(workflowExportName)}Step`,
      usedExportNames,
    );
    const steps: WorkflowStepDescriptor[] = [];
    const usedStepIds = new Set<string>();

    for (const step of task.steps ?? []) {
      if (!step.id) {
        diagnostics.push({
          code: 'task-step-id-unresolved',
          message: `${task.taskId} step ${step.importedIdentifier} must expose a statically resolved id for Vercel Workflow codegen.`,
          taskName: task.name,
          stepExportName: step.importedIdentifier,
        });
        continue;
      }

      if (usedStepIds.has(step.id)) {
        diagnostics.push({
          code: 'task-step-id-duplicate',
          message: `${task.taskId} declares step id ${step.id} more than once.`,
          taskName: task.name,
          stepExportName: step.importedIdentifier,
        });
        continue;
      }
      usedStepIds.add(step.id);

      const stepWords = combineTaskAndStepWords(taskWords, identifierWords(step.id));
      steps.push({
        id: step.id,
        exportName: uniqueIdentifier(`${toLowerCamel(stepWords)}Step`, usedExportNames),
      });
    }

    descriptors.push({
      taskId: task.taskId,
      workflowExportName,
      stepRunnerExportName,
      steps,
    });
  }

  return { descriptors, diagnostics };
};

const renderStepsSource = ({
  descriptors,
  runtimeImportPath,
  stepRunnerImport,
}: {
  descriptors: WorkflowDescriptor[];
  runtimeImportPath: string;
  stepRunnerImport?: ImportReference;
}) => {
  if (descriptors.length === 0) {
    return `${GENERATED_HEADER}\n`;
  }

  const hasSteps = descriptors.some(descriptor => descriptor.steps.length > 0);
  const runtimeImports = [
    '  type TaskStepRunner,',
    ...(hasSteps ? ['  type TaskStepWorkflowInput,'] : []),
    ...(hasSteps && !stepRunnerImport ? ['  runTaskStepInVercelWorkflow,'] : []),
  ].join('\n');
  const stepModules = descriptors
    .map(descriptor => {
      const stepExports = descriptor.steps
        .map(step => {
          const runStep = stepRunnerImport
            ? `const { ${stepRunnerImport.importedIdentifier} } = await import('${stepRunnerImport.importPath}');

  return ${stepRunnerImport.importedIdentifier}(input);`
            : `return runTaskStepInVercelWorkflow(input, ${descriptor.stepRunnerExportName});`;

          return `export async function ${step.exportName}(input: TaskStepWorkflowInput) {
  'use step';

  ${runStep}
}`;
        })
        .join('\n\n');
      const stepSwitchBody =
        descriptor.steps.length > 0
          ? `${descriptor.steps
              .map(step => `    case '${step.id}':\n      return ${step.exportName}(input);`)
              .join(
                '\n',
              )}\n    default:\n      throw new Error(\`Task step "\${input.stepName}" is not generated.\`);`
          : `    default:\n      throw new Error(\`Task "\${input.taskId}" does not declare generated steps.\`);`;

      return `${stepExports ? `${stepExports}\n\n` : ''}export const ${descriptor.stepRunnerExportName}: TaskStepRunner = input => {
  switch (input.stepName) {
${stepSwitchBody}
  }
};`;
    })
    .join('\n\n');

  return `${GENERATED_HEADER}

import {
${runtimeImports}
} from '${runtimeImportPath}';

${stepModules}
`;
};

const renderWorkflowSource = ({
  descriptors,
  runtimeImportPath,
  stepsImportPath,
}: {
  descriptors: WorkflowDescriptor[];
  runtimeImportPath: string;
  stepsImportPath: string;
}) => {
  const runtimeImports =
    descriptors.length > 0
      ? `import {
  type TaskWorkflow,
  type TaskWorkflowInput,
  runTaskInVercelWorkflow,
} from '${runtimeImportPath}';`
      : `import type { TaskWorkflow } from '${runtimeImportPath}';`;
  const stepImports =
    descriptors.length > 0
      ? `import {
${descriptors.map(descriptor => `  ${descriptor.stepRunnerExportName},`).join('\n')}
} from '${stepsImportPath}';`
      : '';
  const workflowExports = descriptors
    .map(
      descriptor => `export async function ${descriptor.workflowExportName}(
  input: TaskWorkflowInput,
) {
  'use workflow';

  return runTaskInVercelWorkflow(input, ${descriptor.stepRunnerExportName});
}`,
    )
    .join('\n\n');
  const registryEntries = descriptors
    .map(descriptor => `  ['${descriptor.taskId}', ${descriptor.workflowExportName}],`)
    .join('\n');

  return `${GENERATED_HEADER}

${runtimeImports}
${stepImports ? `${stepImports}\n` : ''}
${workflowExports ? `${workflowExports}\n\n` : ''}const taskWorkflows = new Map<string, TaskWorkflow>([
${registryEntries}
]);

export const getTaskWorkflow = (taskId: string) => taskWorkflows.get(taskId);
`;
};

export const renderVercelWorkflowModules = ({
  application,
  runtimeImportPath,
  stepsImportPath,
  stepRunnerImport,
  runtime = 'vercel-workflow',
}: VercelWorkflowCodegenOptions): VercelWorkflowCodegenResult => {
  const { descriptors, diagnostics } = createWorkflowDescriptors(application, runtime);

  return {
    diagnostics,
    stepsSource: renderStepsSource({
      descriptors,
      runtimeImportPath,
      ...(stepRunnerImport ? { stepRunnerImport } : {}),
    }),
    workflowSource: renderWorkflowSource({
      descriptors,
      runtimeImportPath,
      stepsImportPath,
    }),
  };
};
