import { execFileSync } from 'node:child_process';

import {
  assert,
  expectedPublicPackageCount,
  prereleaseVersionPattern,
} from '../release/public-packages.mjs';

const runGit = arguments_ => execFileSync('git', arguments_, { encoding: 'utf8' }).trim();

const parseArguments = arguments_ => {
  const [command, ...rest] = arguments_;
  const options = {};

  for (let index = 0; index < rest.length; index += 1) {
    const argument = rest[index];
    if (argument === '--dry-run') {
      assert(options.dryRun === undefined, 'Duplicate --dry-run option.');
      options.dryRun = true;
      continue;
    }

    assert(argument.startsWith('--'), `Unexpected argument: ${argument}.`);
    const key = argument.slice(2);
    assert(options[key] === undefined, `Duplicate --${key} option.`);
    const value = rest[index + 1];
    assert(value && !value.startsWith('--'), `Missing value for --${key}.`);
    options[key] = value;
    index += 1;
  }

  return { command, options };
};

const packageVersionAt = (reference, directory) => {
  const manifest = JSON.parse(runGit(['show', `${reference}:packages/${directory}/package.json`]));
  assert(manifest.private !== true, `packages/${directory} must remain public.`);
  return manifest.version;
};

const releaseVersionAt = reference => {
  const directories = runGit(['ls-tree', '-d', '--name-only', `${reference}:packages`])
    .split('\n')
    .filter(Boolean)
    .filter(directory => {
      try {
        runGit(['cat-file', '-e', `${reference}:packages/${directory}/package.json`]);
        return true;
      } catch {
        return false;
      }
    });

  const publicVersions = directories.map(directory => packageVersionAt(reference, directory));
  assert(
    publicVersions.length === expectedPublicPackageCount,
    `Expected ${expectedPublicPackageCount} public package manifests, found ${publicVersions.length}.`,
  );
  const versions = new Set(publicVersions);
  assert(versions.size === 1, 'The generated release must keep every package in lockstep.');
  const [version] = versions;
  assert(prereleaseVersionPattern.test(version), `${version} is not an alpha or next prerelease.`);
  return version;
};

const allowedGeneratedPath = filePath =>
  /^packages\/[^/]+\/(?:CHANGELOG\.md|package\.json)$/.test(filePath) ||
  /^\.changeset\/(?:[^/]+\.md|pre\/[^/]+\.md|pre\.json)$/.test(filePath);

const validate = options => {
  const base = options.base ?? 'origin/main';
  const head = options.head ?? 'HEAD';
  const changedPaths = runGit(['diff', '--name-only', `${base}...${head}`])
    .split('\n')
    .filter(Boolean);

  assert(changedPaths.length > 0, 'The release pull request contains no generated changes.');
  const unexpectedPaths = changedPaths.filter(filePath => !allowedGeneratedPath(filePath));
  assert(
    unexpectedPaths.length === 0,
    `Release pull requests may contain generated release files only:\n${unexpectedPaths.join('\n')}`,
  );

  const authorEmails = runGit(['log', '--format=%ae', `${base}..${head}`])
    .split('\n')
    .filter(Boolean);
  assert(authorEmails.length > 0, 'The release pull request contains no commits.');
  const unexpectedAuthors = [
    ...new Set(
      authorEmails.filter(
        email => !/^\d+\+github-actions\[bot\]@users\.noreply\.github\.com$/.test(email),
      ),
    ),
  ];
  assert(
    unexpectedAuthors.length === 0,
    `Release pull request commits must be generated by GitHub Actions:\n${unexpectedAuthors.join('\n')}`,
  );

  const pendingChangesets = runGit(['ls-tree', '--name-only', `${head}:.changeset`])
    .split('\n')
    .filter(fileName => fileName.endsWith('.md') && fileName !== 'README.md');
  assert(
    pendingChangesets.length === 0,
    `Generated release still contains unconsumed changesets:\n${pendingChangesets.join('\n')}`,
  );

  const version = releaseVersionAt(head);
  process.stdout.write(`Validated generated Ontahi release ${version}.\n`);
};

const githubRequest = async (path, options = {}) => {
  const token = process.env.GITHUB_TOKEN;
  const repository = process.env.GITHUB_REPOSITORY;
  assert(token, 'Missing GITHUB_TOKEN.');
  assert(repository, 'Missing GITHUB_REPOSITORY.');

  const response = await fetch(`https://api.github.com/repos/${repository}${path}`, {
    ...options,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'X-GitHub-Api-Version': '2022-11-28',
      ...options.headers,
    },
  });
  assert(response.ok, `GitHub ${options.method ?? 'GET'} ${path} failed: ${response.status}.`);
  return response.status === 204 ? undefined : response.json();
};

const releaseNotesFrom = body => {
  const marker = '# Releases';
  const markerIndex = body.indexOf(marker);
  assert(markerIndex >= 0, 'Changesets did not generate a Releases section.');
  return body.slice(markerIndex).trim();
};

const releaseVersionFrom = releaseNotes => {
  const versions = [
    ...releaseNotes.matchAll(/^## @ontahi\/[\w-]+@(\d+\.\d+\.\d+-(?:alpha|next)\.\d+)$/gm),
  ].map(match => match[1]);
  assert(versions.length > 0, 'Could not derive a prerelease version from the generated notes.');
  assert(
    new Set(versions).size === 1,
    'Generated release notes contain multiple package versions.',
  );
  return versions[0];
};

const update = async options => {
  const pullRequestNumber = process.env.VERSION_PR_NUMBER;
  assert(pullRequestNumber, 'Missing VERSION_PR_NUMBER.');
  const pullRequest = await githubRequest(`/pulls/${pullRequestNumber}`);
  const releaseNotes = releaseNotesFrom(pullRequest.body ?? '');
  const version = releaseVersionFrom(releaseNotes);
  const title = `Release Ontahi ${version}`;
  const body = [
    `This bot-owned pull request prepares **Ontahi ${version}** from the changesets already merged into \`main\`.`,
    '',
    'Its commits and release files are generated. Merge it when the accumulated notes are ready; GitHub Actions will validate the candidate, publish every package through npm trusted publishing, and create the matching tag and GitHub prerelease.',
    '',
    releaseNotes,
    '',
  ].join('\n');

  if (options.dryRun) {
    process.stdout.write(`${JSON.stringify({ title, body }, null, 2)}\n`);
    return;
  }

  await githubRequest(`/pulls/${pullRequestNumber}`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ title, body }),
  });
  process.stdout.write(`Updated release pull request #${pullRequestNumber} for ${version}.\n`);
};

const { command, options } = parseArguments(process.argv.slice(2));

if (command === 'validate') validate(options);
else if (command === 'update') await update(options);
else throw new Error('Expected one of: validate, update.');
