import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  launcher: {
    position: 'fixed',
    zIndex: 2147483646,
    right: 18,
    bottom: 18,
    display: 'grid',
    width: 50,
    height: 50,
    padding: 0,
    placeItems: 'center',
    overflow: 'hidden',
    border: '1px solid rgba(217, 76, 67, 0.48)',
    borderRadius: 16,
    color: '#f6f2eb',
    background: '#162018',
    boxShadow: '0 16px 44px rgba(7, 17, 13, 0.32)',
    cursor: 'pointer',
  },
  launcherIcon: { display: 'block', width: 34, height: 34 },
  panel: {
    position: 'fixed',
    zIndex: 2147483646,
    right: 12,
    bottom: 12,
    left: 12,
    display: 'grid',
    width: 'auto',
    maxWidth: 1480,
    height: 'min(620px, calc(100vh - 24px))',
    margin: '0 auto',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    overflow: 'hidden',
    border: '1px solid #2d4a3d',
    borderRadius: 18,
    color: '#dce8e1',
    background: '#0c1310',
    boxShadow: '0 26px 80px rgba(3, 10, 7, 0.52)',
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    fontSize: 12,
    textAlign: 'left',
  },
  header: {
    display: 'flex',
    minHeight: 58,
    alignItems: 'center',
    gap: 22,
    padding: '0 16px',
    borderBottom: '1px solid #213229',
    background: '#101a15',
  },
  brand: { display: 'grid', flex: '0 0 auto', gap: 2 },
  eyebrow: {
    color: '#7aa58f',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
  },
  title: { margin: 0, color: '#effbf4', fontSize: 15, fontWeight: 800 },
  views: { display: 'flex', gap: 4 },
  view: {
    minHeight: 32,
    padding: '0 12px',
    border: 0,
    borderRadius: 9,
    color: '#80978b',
    background: 'transparent',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 750,
  },
  activeView: { color: '#dffbea', background: '#193226' },
  count: {
    display: 'inline-grid',
    minWidth: 18,
    height: 18,
    marginLeft: 7,
    placeItems: 'center',
    borderRadius: 999,
    color: '#98b9a8',
    background: '#0c1812',
    fontSize: 9,
  },
  headerActions: { display: 'flex', marginLeft: 'auto', gap: 7 },
  subtleButton: {
    minHeight: 30,
    padding: '0 10px',
    border: '1px solid #30463a',
    borderRadius: 9,
    color: '#a9c2b5',
    background: '#14221b',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 700,
  },
  workspace: {
    display: 'grid',
    minWidth: 0,
    minHeight: 0,
    gridTemplateColumns: 'minmax(290px, 0.34fr) minmax(0, 1fr)',
  },
  sidebar: {
    display: 'grid',
    minWidth: 0,
    minHeight: 0,
    gridTemplateRows: 'auto minmax(0, 1fr)',
    borderRight: '1px solid #213229',
    background: '#0b120f',
  },
  filterBar: { padding: 10, borderBottom: '1px solid #213229', background: '#0d1712' },
  filter: {
    boxSizing: 'border-box',
    width: '100%',
    height: 34,
    padding: '0 11px',
    border: '1px solid #293d32',
    borderRadius: 9,
    outline: 0,
    color: '#dce8e1',
    background: '#09110d',
    font: 'inherit',
  },
  list: {
    minHeight: 0,
    margin: 0,
    padding: 8,
    overflow: 'auto',
    listStyle: 'none',
    scrollbarGutter: 'stable',
  },
  row: {
    display: 'grid',
    boxSizing: 'border-box',
    width: '100%',
    gridTemplateColumns: '8px minmax(0, 1fr)',
    gap: 10,
    alignItems: 'center',
    margin: 0,
    padding: '11px 9px',
    border: 0,
    borderRadius: 10,
    color: '#d7e3dc',
    background: 'transparent',
    cursor: 'pointer',
    font: 'inherit',
    textAlign: 'left',
  },
  selectedRow: { background: '#16291f' },
  dot: { width: 7, height: 7, borderRadius: 999, background: '#d6a75d' },
  rowMain: { display: 'grid', minWidth: 0, gap: 4 },
  rowTitle: {
    overflow: 'hidden',
    color: '#ebf4ef',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    fontWeight: 750,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowMeta: {
    display: 'flex',
    gap: 7,
    overflow: 'hidden',
    color: '#6f897c',
    fontSize: 10,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  family: {
    color: '#8eb49f',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  },
  empty: {
    display: 'grid',
    minHeight: 180,
    placeItems: 'center',
    padding: 28,
    color: '#6d8679',
    textAlign: 'center',
  },
  detail: { display: 'grid', minWidth: 0, minHeight: 0, gridTemplateRows: 'auto minmax(0, 1fr)' },
  detailHeader: {
    display: 'flex',
    minWidth: 0,
    minHeight: 54,
    alignItems: 'center',
    gap: 14,
    padding: '0 15px',
    borderBottom: '1px solid #213229',
    background: '#0e1813',
  },
  detailHeadingGroup: { display: 'grid', minWidth: 0, gap: 3 },
  detailTitle: {
    margin: 0,
    overflow: 'hidden',
    color: '#effbf4',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 13,
    fontWeight: 800,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  detailMeta: { display: 'flex', gap: 9, color: '#6f897c', fontSize: 10 },
  payloadGrid: {
    display: 'grid',
    minWidth: 0,
    minHeight: 0,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
  },
  payloadPanel: {
    display: 'grid',
    minWidth: 0,
    minHeight: 0,
    gridTemplateRows: 'auto minmax(0, 1fr)',
    borderRight: '1px solid #213229',
  },
  payloadHeader: {
    display: 'flex',
    minHeight: 42,
    alignItems: 'center',
    gap: 10,
    padding: '0 11px',
    borderBottom: '1px solid #1b2a22',
    background: '#0b1410',
  },
  payloadTitle: {
    margin: 0,
    color: '#a7c8b6',
    fontSize: 9,
    fontWeight: 850,
    letterSpacing: '0.11em',
    textTransform: 'uppercase',
  },
  modes: {
    display: 'flex',
    marginLeft: 'auto',
    padding: 2,
    border: '1px solid #26392f',
    borderRadius: 8,
    background: '#09110d',
  },
  mode: {
    minHeight: 25,
    padding: '0 7px',
    border: 0,
    borderRadius: 6,
    color: '#6f897c',
    background: 'transparent',
    cursor: 'pointer',
    font: 'inherit',
    fontSize: 9,
    fontWeight: 750,
  },
  activeMode: { color: '#dffbea', background: '#1a3025' },
  payloadBody: {
    minWidth: 0,
    minHeight: 0,
    overflow: 'auto',
    padding: 14,
    background: '#09100d',
    scrollbarGutter: 'stable',
  },
  semanticHeadline: {
    margin: '0 0 14px',
    color: '#e9fff2',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 14,
    fontWeight: 800,
    lineHeight: 1.45,
  },
  semanticGrid: { display: 'grid', gap: 10 },
  semanticSection: { display: 'grid', gap: 10 },
  semanticCard: {
    padding: 11,
    border: '1px solid #1f3128',
    borderRadius: 10,
    background: '#0e1813',
  },
  semanticLabel: {
    display: 'block',
    marginBottom: 6,
    color: '#6f9581',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  semanticValue: {
    color: '#c8ded2',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    lineHeight: 1.55,
  },
  chips: { display: 'flex', flexWrap: 'wrap', gap: 5 },
  chip: {
    padding: '3px 6px',
    border: '1px solid #294236',
    borderRadius: 6,
    color: '#add0bd',
    background: '#13231b',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 10,
  },
  tableWrap: { overflow: 'auto', border: '1px solid #1f3128', borderRadius: 10 },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 10 },
  tableCell: {
    maxWidth: 180,
    padding: '7px 9px',
    overflow: 'hidden',
    borderBottom: '1px solid #19271f',
    color: '#b8cec2',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  runBody: {
    minWidth: 0,
    minHeight: 0,
    overflow: 'auto',
    padding: 16,
    background: '#09100d',
    scrollbarGutter: 'stable',
  },
  runSummary: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 8,
    marginBottom: 14,
  },
  messageList: { display: 'grid', gap: 7, margin: 0, padding: 0, listStyle: 'none' },
  message: {
    overflow: 'hidden',
    border: '1px solid #1f3128',
    borderRadius: 10,
    background: '#0d1712',
  },
  messageSummary: {
    display: 'grid',
    gridTemplateColumns: '24px 8px minmax(0, 1fr) auto',
    gap: 9,
    alignItems: 'center',
    padding: '10px 11px',
    cursor: 'pointer',
    listStyle: 'none',
  },
  messageDirection: {
    color: '#6f9581',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 12,
    fontWeight: 800,
  },
  messageMain: { display: 'grid', minWidth: 0, gap: 3 },
  messageTitle: {
    overflow: 'hidden',
    color: '#d8e9e0',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    fontWeight: 750,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  messageMeta: { color: '#6f897c', fontSize: 9 },
  messagePayload: { padding: 12, borderTop: '1px solid #1f3128', background: '#09110d' },
  pre: {
    margin: 0,
    color: '#bcd4c7',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 10,
    lineHeight: 1.55,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  copyButton: {
    position: 'sticky',
    top: 0,
    zIndex: 1,
    float: 'right',
    minHeight: 26,
    margin: '0 0 8px 8px',
    padding: '0 8px',
    border: '1px solid #30463a',
    borderRadius: 7,
    color: '#9ebbad',
    background: '#14221b',
    cursor: 'pointer',
    font: 'inherit',
    fontSize: 9,
    fontWeight: 750,
  },
  settingsPage: {
    minWidth: 0,
    minHeight: 0,
    overflow: 'auto',
    padding: 20,
    background: '#09100d',
    scrollbarGutter: 'stable',
  },
};
