import type { CSSProperties } from 'react';

export const transportSettingsStyles: Record<string, CSSProperties> = {
  root: { display: 'grid', gap: 18, maxWidth: 1080, margin: '0 auto' },
  header: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 24,
  },
  heading: { display: 'grid', gap: 5 },
  eyebrow: {
    color: '#7aa58f',
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
  },
  title: { margin: 0, color: '#effbf4', fontSize: 18, fontWeight: 800 },
  description: { maxWidth: 650, margin: 0, color: '#789083', fontSize: 11, lineHeight: 1.55 },
  summary: {
    flex: '0 0 auto',
    padding: '7px 10px',
    border: '1px solid #294236',
    borderRadius: 999,
    color: '#add0bd',
    background: '#13231b',
    fontSize: 10,
    fontWeight: 750,
  },
  presets: { display: 'flex', flexWrap: 'wrap', gap: 7 },
  preset: {
    minHeight: 30,
    padding: '0 10px',
    border: '1px solid #30463a',
    borderRadius: 8,
    color: '#93aa9e',
    background: '#101a15',
    cursor: 'pointer',
    font: 'inherit',
    fontSize: 10,
    fontWeight: 750,
  },
  activePreset: { border: '1px solid #46745c', color: '#dffbea', background: '#193226' },
  routeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 300px), 1fr))',
    gap: 9,
  },
  route: {
    display: 'grid',
    gridTemplateColumns: '36px minmax(0, 1fr) minmax(110px, auto)',
    gap: 11,
    alignItems: 'center',
    padding: 12,
    border: '1px solid #1f3128',
    borderRadius: 11,
    background: '#0e1813',
  },
  routeIcon: {
    display: 'grid',
    width: 32,
    height: 32,
    placeItems: 'center',
    border: '1px solid #294236',
    borderRadius: 9,
    color: '#9ec8b1',
    background: '#13231b',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 9,
    fontWeight: 850,
    textTransform: 'uppercase',
  },
  routeCopy: { display: 'grid', minWidth: 0, gap: 3 },
  routeLabel: { color: '#dce8e1', fontSize: 11, fontWeight: 800 },
  capability: {
    color: '#80ab94',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 9,
  },
  routeDescription: { color: '#6f897c', fontSize: 9, lineHeight: 1.4 },
  select: {
    minWidth: 110,
    height: 32,
    padding: '0 8px',
    border: '1px solid #30463a',
    borderRadius: 8,
    outline: 0,
    color: '#c7ddd1',
    background: '#0a120e',
    font: 'inherit',
    fontSize: 10,
  },
};
