const portableOperationEntries = operations =>
  operations.flatMap(operation =>
    operation.conditions?.pre?.length && operation.entityName
      ? [
          [
            `${operation.entityName}.${operation.name}`,
            {
              pre: operation.conditions.pre.map(condition => ({
                name: condition.name,
                expression: condition.expression,
              })),
            },
          ],
        ]
      : [],
  );

const portableDerivedEntities = entities =>
  Object.fromEntries(
    entities.flatMap(entity =>
      entity.entitySchemaProjection?.derivedFields?.length
        ? [
            [
              entity.entityName,
              {
                fields: Object.fromEntries(
                  entity.entitySchemaProjection.derivedFields.map(field => [
                    field.name,
                    field.expression,
                  ]),
                ),
              },
            ],
          ]
        : [],
    ),
  );

export const renderGeneratedOperationConditionRegistryModule = ({ operations, entities = [] }) => {
  const declaration = {
    version: 1,
    operations: Object.fromEntries(portableOperationEntries(operations)),
  };

  const derivedDeclaration = {
    version: 1,
    entities: portableDerivedEntities(entities),
  };

  return `// This file is generated by @ontahi/codegen. Do not edit by hand.

import { definePortableDerivedFieldRegistry, definePortableOperationConditionRegistry } from '@ontahi/core/data-graph';

export const derivedFields = definePortableDerivedFieldRegistry(${JSON.stringify(
    derivedDeclaration,
    null,
    2,
  )});

export const operationConditions = definePortableOperationConditionRegistry(${JSON.stringify(
    declaration,
    null,
    2,
  )});
`;
};
