const portableOperationEntries = operations =>
  operations.flatMap(operation =>
    operation.conditions?.pre?.length && operation.entityName
      ? [
          [
            `${operation.entityName}.${operation.name}`,
            {
              pre: operation.conditions.pre.map(condition => ({
                name: condition.name,
                expression: condition.expression,
              })),
            },
          ],
        ]
      : [],
  );

export const renderGeneratedOperationConditionRegistryModule = ({ operations }) => {
  const declaration = {
    version: 1,
    operations: Object.fromEntries(portableOperationEntries(operations)),
  };

  return `// This file is generated by @ontahi/codegen. Do not edit by hand.

import { definePortableOperationConditionRegistry } from '@ontahi/core/data-graph';

export const operationConditions = definePortableOperationConditionRegistry(${JSON.stringify(
    declaration,
    null,
    2,
  )});
`;
};
